### ISSUE TITLE
[Korekto][Daily] Votre note actuelle : 26/26

### ISSUE THREAD

**Issue by korekto-agent** [ShaanksM/java_api_training#1]
# Exercice commencé
Votre note est de **26**/26.  

## Détail
* Part 1 - Compilation & Tests: 4/4
* Part 2 - CI: 1/1
* Part 3 - Test Coverage: 3/3
* Part 4 - Ping: 2/2
* Part 5 - Start Game API (server): 3/3
* Part 6 - Start Game API (client): 2/2
* Part 7 - Fire API (client): 4/4
* Part 8 - Fire API (server): 2/2
* Part 9 - Game self convergence: 5/5
* Git (proper descriptive messages): 0
    * OK

* Coding style: 0
    * OK

Vous avez jusqu'à 2021-07-11T19:59:00Z pour améliorer votre note.

*Analyse effectuée à 2021-07-05T14:41:29.687945900Z.*

**Comment by ShaanksM** [comment]
k

**Comment by ShaanksM** [comment]
Au sujet de la " propreté description du git " , j'aurais toujours le -1 point ? Ou alors je peux " recommencer " le projet pour changer ce nom ? Car c'est un ancien commit et ces descriptions ( " Update " et " Implémentation " ) se sont fait écraser par d'autres commits
